configure daily rotate to match config for snapshot

diff --git a/snapshot_daily_rotate b/snapshot_daily_rotate
--- a/snapshot_daily_rotate
+++ b/snapshot_daily_rotate
@@ -1,69 +1,69 @@
 #!/bin/bash
 # ----------------------------------------------------------------------
-# mikes handy rotating-filesystem-snapshot utility: daily snapshots
+# snapshot daily rotate
 # ----------------------------------------------------------------------
-# intended to be run daily as a cron job when hourly.3 contains the
-# midnight (or whenever you want) snapshot; say, 13:00 for 4-hour snapshots.
+# intended to be run daily as a cron job to convert most recent hourly
+# snapshot to newest daily snapshot
 # ----------------------------------------------------------------------
 
+# avoid accidental use of $PATH
 unset PATH
 
 # ------------- system commands used by this script --------------------
+
 ID=/usr/bin/id;
 ECHO=/bin/echo;
-
-MOUNT=/bin/mount;
+HDIUTIL=/usr/bin/hdiutil
 RM=/bin/rm;
 MV=/bin/mv;
-CP=/bin/cp;
+FIND=/usr/bin/find;
+CPIO=/usr/bin/cpio;
 
 # ------------- file locations -----------------------------------------
 
-MOUNT_DEVICE=/dev/hdb1;
-SNAPSHOT_RW=/root/snapshot;
+SPARSE_BUNDLE=/Volumes/Ganymede/backups/jove.sparsebundle
+SNAPSHOT_RW=/Volumes/backup
 
 # ------------- the script itself --------------------------------------
 
 # make sure we're running as root
-if (( `$ID -u` != 0 )); then { $ECHO "Sorry, must be root.  Exiting..."; exit; } fi
-
-# attempt to remount the RW mount point as RW; else abort
-$MOUNT -o remount,rw $MOUNT_DEVICE $SNAPSHOT_RW ;
-if (( $? )); then
-{
-  $ECHO "snapshot: could not remount $SNAPSHOT_RW readwrite";
+if (( `$ID -u` != 0 )); then
+  $ECHO "snapshot: Sorry, must be root...";
   exit;
-}
+fi;
+
+# attempt to mount the sparseimage; else abort
+$HDIUTIL attach -noverify $SPARSE_BUNDLE
+if (( $? )); then
+  $ECHO "snapshot: Could not mount $SNAPSHOT_RW";
+  exit;
 fi;
 
 
 # step 1: delete the oldest snapshot, if it exists:
-if [ -d $SNAPSHOT_RW/home/daily.2 ] ; then      \
-$RM -rf $SNAPSHOT_RW/home/daily.2 ;       \
+if [ -d $SNAPSHOT_RW/daily.4 ] ; then
+  $RM -rf $SNAPSHOT_RW/daily.4;
 fi ;
 
 # step 2: shift the middle snapshots(s) back by one, if they exist
-if [ -d $SNAPSHOT_RW/home/daily.1 ] ; then      \
-$MV $SNAPSHOT_RW/home/daily.1 $SNAPSHOT_RW/home/daily.2 ; \
+if [ -d $SNAPSHOT_RW/daily.3 ] ; then
+  $MV $SNAPSHOT_RW/daily.3 $SNAPSHOT_RW/daily.4;
 fi;
-if [ -d $SNAPSHOT_RW/home/daily.0 ] ; then      \
-$MV $SNAPSHOT_RW/home/daily.0 $SNAPSHOT_RW/home/daily.1;  \
+if [ -d $SNAPSHOT_RW/daily.2 ] ; then
+  $MV $SNAPSHOT_RW/daily.2 $SNAPSHOT_RW/daily.3;
+fi;
+if [ -d $SNAPSHOT_RW/daily.1 ] ; then
+  $MV $SNAPSHOT_RW/daily.1 $SNAPSHOT_RW/daily.2;
+fi;
+if [ -d $SNAPSHOT_RW/daily.0 ] ; then
+  $MV $SNAPSHOT_RW/daily.0 $SNAPSHOT_RW/daily.1;
 fi;
 
 # step 3: make a hard-link-only (except for dirs) copy of
 # hourly.3, assuming that exists, into daily.0
-if [ -d $SNAPSHOT_RW/home/hourly.3 ] ; then     \
-$CP -al $SNAPSHOT_RW/home/hourly.3 $SNAPSHOT_RW/home/daily.0 ;  \
+if [ -d $SNAPSHOT_RW/hourly.3 ] ; then
+  cd $SNAPSHOT_RW/hourly.3 && $FIND . -print | $CPIO -pal ../daily.0;
 fi;
 
-# note: do *not* update the mtime of daily.0; it will reflect
-# when hourly.3 was made, which should be correct.
-
-# now remount the RW snapshot mountpoint as readonly
-
-$MOUNT -o remount,ro $MOUNT_DEVICE $SNAPSHOT_RW ;
-if (( $? )); then
-{
-  $ECHO "snapshot: could not remount $SNAPSHOT_RW readonly";
-  exit;
-} fi;
+# all done!
+$HDIUTIL detach $SNAPSHOT_RW
